[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[project]
name = "argparsecfg"
description = "argparse config."
readme = "README.md"
requires-python = ">=3.10,<3.15"
authors = [{ name = "Yasyrev Andrei", email = "a.yasyrev@gmail.com" }]
license = { text = "Apache-2.0" }
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]
version = "0.2.5b1"
dependencies = []

[project.urls]
Homepage = "https://github.com/ayasyrev/argparsecfg"

[dependency-groups]
dev = [
  "black",
  "black[jupyter]",
  "flake8",
  "isort",
  "mypy",
  "nbmetaclean",
  "nox",
  "pre-commit",
  "ruff",
]
test = [
  "pytest",
  "pytest-cov",
  "coverage[toml]",
]
docs = [
  "nbdocs",
]

[tool.uv]
prerelease = "allow"
